CREATE SEQUENCE seq_citizen_id
    START WITH 1001
    INCREMENT BY 1
    MINVALUE 1001
    NOCYCLE;

CREATE SEQUENCE seq_vehicle_id
    START WITH 2001
    INCREMENT BY 1
    MINVALUE 2001
    NOCYCLE;

CREATE SEQUENCE seq_officer_id
    START WITH 3001
    INCREMENT BY 1
    MINVALUE 3001
    NOCYCLE;

CREATE SEQUENCE seq_location_id
    START WITH 4001
    INCREMENT BY 1
    MINVALUE 4001
    NOCYCLE;

CREATE SEQUENCE seq_challan_id
    START WITH 5001
    INCREMENT BY 1
    MINVALUE 5001
    NOCYCLE;

CREATE SEQUENCE seq_payment_id
    START WITH 6001
    INCREMENT BY 1
    MINVALUE 6001
    NOCYCLE;

